# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AEPEdgeConsent', '~> 4.0'
  pod 'AEPAssurance', '~> 4.0'
  pod 'AEPEdgeIdentity', '~> 4.0'
  pod 'AEPEdge', '~> 4.0'
  pod 'AEPUserProfile', '~> 4.0'
  pod 'AEPCore', '~> 4.0'
  pod 'AEPIdentity', '~> 4.0'
  pod 'AEPSignal', '~>4.0'
  pod 'AEPLifecycle', '~>4.0'
  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
